/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                'tertiary-container': '#e3dbfd',
                'surface-container-low': '#f0f4f7',
                'primary-fixed-dim': '#c5d4ff',
                'surface-variant': '#d9e4ea',
                'on-tertiary': '#fcf7ff',
                'primary-container': '#dae2ff',
                background: '#f7f9fb',
                'on-primary-fixed-variant': '#2056ba',
                'tertiary-fixed': '#e3dbfd',
                'primary-fixed': '#dae2ff',
                'error-container': '#fe8983',
                'secondary-fixed': '#d5e3fc',
                'primary-dim': '#0f4db0',
                'secondary-dim': '#465468',
                tertiary: '#605c78',
                'surface-container-high': '#e1e9ee',
                'on-secondary-fixed': '#324053',
                'on-error-container': '#752121',
                'on-tertiary-container': '#514d68',
                'outline-variant': '#a9b4b9',
                'inverse-on-surface': '#9a9d9f',
                'surface-bright': '#f7f9fb',
                'surface-container': '#e8eff3',
                'inverse-primary': '#6995fd',
                'on-primary-container': '#0d4cb0',
                'surface-container-lowest': '#ffffff',
                primary: '#2559bd',
                'on-primary-fixed': '#003a8f',
                secondary: '#526074',
                surface: '#f7f9fb',
                'tertiary-fixed-dim': '#d4cdee',
                'inverse-surface': '#0b0f10',
                'tertiary-dim': '#54506b',
                'on-primary': '#f8f7ff',
                'error-dim': '#4e0309',
                'on-secondary': '#f8f8ff',
                error: '#9f403d',
                'secondary-fixed-dim': '#c7d5ed',
                'on-background': '#2a3439',
                'on-surface': '#2a3439',
                'surface-dim': '#cfdce3',
                'secondary-container': '#d5e3fc',
                'surface-tint': '#2559bd',
                'on-secondary-fixed-variant': '#4e5c71',
                outline: '#717c82',
                'on-surface-variant': '#566166',
                'on-tertiary-fixed-variant': '#5b5672',
                'on-tertiary-fixed': '#3e3a54',
                'on-error': '#fff7f6',
                'on-secondary-container': '#455367',
                'surface-container-highest': '#d9e4ea'
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            fontFamily: {
                headline: ['Inter'],
                body: ['Inter'],
                label: ['Inter'],
            },
        },
    },
    plugins: [],
}
