/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                'on-error': '#690005',
                'error-container': '#93000a',
                'surface-dim': '#0b1326',
                'surface-variant': '#2d3449',
                surface: '#0b1326',
                'surface-container': '#171f33',
                'secondary-fixed': '#d3e4fe',
                error: '#ffb4ab',
                'on-surface': '#dae2fd',
                'on-background': '#dae2fd',
                'primary-container': '#6d88ff',
                'primary-fixed': '#dde1ff',
                'surface-container-high': '#222a3d',
                outline: '#8b90a0',
                'surface-container-highest': '#2d3449',
                background: '#0b1326',
                'surface-bright': '#31394d',
                'on-primary-container': '#001e78',
                'on-secondary-container': '#a9bad3',
                'on-primary-fixed-variant': '#0035be',
                'on-error-container': '#ffdad6',
                'primary-fixed-dim': '#b8c3ff',
                tertiary: '#00dbe9',
                'tertiary-fixed': '#7df4ff',
                'secondary-container': '#3a4a5f',
                'surface-container-low': '#131b2e',
                'surface-container-lowest': '#060e20',
                'tertiary-fixed-dim': '#00dbe9',
                primary: '#b8c3ff',
                'inverse-on-surface': '#283044',
                'on-tertiary': '#00363a',
                'on-tertiary-fixed-variant': '#004f54',
                'on-primary-fixed': '#001356',
                'on-surface-variant': '#c1c6d7',
                'on-tertiary-fixed': '#002022',
                secondary: '#b7c8e1',
                'inverse-primary': '#124af0',
                'on-secondary-fixed': '#0b1c30',
                'secondary-fixed-dim': '#b7c8e1',
                'on-secondary-fixed-variant': '#38485d',
                'on-secondary': '#213145',
                'on-primary': '#002388',
                'outline-variant': '#414755',
                'inverse-surface': '#dae2fd',
                'on-tertiary-container': '#002f33',
                'surface-tint': '#b8c3ff',
                'tertiary-container': '#00a0aa',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            fontFamily: {
                headline: ['Manrope'],
                body: ['Manrope'],
                label: ['Manrope'],
            },
        },
    },
    plugins: [],
}
